server:
  port: 10000
spring:
  application:
    name: scw-webui
  redis: 
    host: 47.116.5.173
    port: 16379
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false # 开发的时候禁用缓存  
  session:
    timeout: 1800
    store-type: redis
      
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.146.1